services:
  kafka:
    image: apache/kafka:3.9.0
    ports:
      - "9092:9092"
  ui:
    image: ghcr.io/kafbat/kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
